apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: demo-voting-app
    app: redis-service
spec:
  selector:
    app: redis-pod
    name: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
