apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment-app
    env: prod
    tier: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-pod-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: pod-name
      labels:
        app: my-pod-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
    
