apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    app: my-pod-app
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
