apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: demo-voting-app
    app: postgres-service
spec:
  selector:
    app: postgres-pod
    name: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432
