apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: demo-voting-app
    app: voting-app-service
spec:
  selector:
    app: voting-app-pod
    name: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
